package ventanas;

import com.mycompany.proyectofinalprogramacion.encuentro.Encuentro;
import com.mycompany.proyectofinalprogramacion.encuentro.EncuentroDAO;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import pronostica.Pronostica;
import pronostica.PronosticaDAO;

/**
 *
 * @author Nicolas Ribeiro
 */
public class MainWindow extends javax.swing.JFrame {
    
    private DefaultListModel<String> eventListModel = new DefaultListModel<>();
    private EncuentroDAO encuentroDao = new EncuentroDAO();
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        _initialState();
        
        eventList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                _eventListValueChanged(evt);
            }
        });
    }
    
    
    private void _eventListValueChanged(ListSelectionEvent evt) {
        eventPanel.setVisible(true);
        List<Encuentro> encuentroList = encuentroDao.listar();
        
        int encuentroSelectedIndex = eventList.getSelectedIndex();
        
        System.out.println("Indice seleccionado: " + encuentroSelectedIndex);
        Encuentro encuentroSelected = encuentroList.get(encuentroSelectedIndex);
        
        eventTitle.setText("Encuentro: "+(encuentroSelectedIndex+1));
        localTeamName.setText(encuentroSelected.getNombreLocal());
        visitTeamName.setText(encuentroSelected.getNombreVisita());
        eventIdFromLabel.setText(Integer.toString(encuentroSelected.getIdEncuentro()));
    }
    
    public void _initialState(){
        eventPanel.setVisible(false);
        eventIdFromLabel.setVisible(false);
        eventList.setModel(eventListModel);
        List<Encuentro> encuentroList = encuentroDao.listar();

        for(int i = 0; i < encuentroList.size(); i++){
            
            if(!encuentroList.get(i).getEstado().equals("finalizado")){
                String element = (i+1) + ") " + "Local: "+ encuentroList.get(i).getNombreLocal() + " - Visitante: " + encuentroList.get(i).getNombreVisita();
                eventListModel.addElement(element);    
            }
        }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        eventPanel = new javax.swing.JPanel();
        eventTitle = new javax.swing.JLabel();
        localFieldGoals = new javax.swing.JTextField();
        visitFieldGoals = new javax.swing.JTextField();
        localTeamName = new javax.swing.JLabel();
        visitTeamName = new javax.swing.JLabel();
        addBet = new javax.swing.JButton();
        lblVersus = new javax.swing.JLabel();
        eventIdFromLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profileBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Tabla de Pronosticos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 367, -1));

        eventList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Encuentro 1:  Barcelona - Madrid", "Encuentro 2:  Peñarol - Nacional", "Encuentro 3:  Argentina - Mexico", "Encuentro 4:  Alemania - Brasil" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(eventList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 367, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 6, 10, 210));

        lblPoints.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblPoints.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPoints.setText("Puntos: 0");
        getContentPane().add(lblPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 6, 210, 42));

        eventPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eventPanel.setMinimumSize(new java.awt.Dimension(374, 175));

        eventTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventTitle.setText("Encuentro 1");

        localFieldGoals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localFieldGoalsActionPerformed(evt);
            }
        });

        localTeamName.setText("Barcelona");

        visitTeamName.setText("Madrid");

        addBet.setBackground(new java.awt.Color(0, 102, 204));
        addBet.setText("Añadir Pronostico");
        addBet.setOpaque(true);
        addBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBetActionPerformed(evt);
            }
        });

        lblVersus.setText("VS");

        eventIdFromLabel.setText("jLabel4");

        javax.swing.GroupLayout eventPanelLayout = new javax.swing.GroupLayout(eventPanel);
        eventPanel.setLayout(eventPanelLayout);
        eventPanelLayout.setHorizontalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localFieldGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(localTeamName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVersus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitFieldGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(visitTeamName)))
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addComponent(eventTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eventIdFromLabel)))
                .addContainerGap())
        );
        eventPanelLayout.setVerticalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventTitle)
                    .addComponent(eventIdFromLabel))
                .addGap(44, 44, 44)
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localTeamName)
                    .addComponent(visitTeamName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localFieldGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitFieldGoals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVersus))
                .addGap(18, 18, 18)
                .addComponent(addBet, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(eventPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 6, -1, 210));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 6, 10, 210));

        profileBtn.setText("Perfil");
        getContentPane().add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(803, 189, 223, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localFieldGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localFieldGoalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localFieldGoalsActionPerformed

    private void addBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBetActionPerformed
        String mockLogin = "test";
        String localInputValue = localFieldGoals.getText();
        String visitInputValue = visitFieldGoals.getText();
        String eventId = eventIdFromLabel.getText();
        
        Pronostica pronostico = new Pronostica(mockLogin, Integer.parseInt(eventId), Integer.parseInt(localInputValue), Integer.parseInt(visitInputValue));
        PronosticaDAO pronosticaDao = new PronosticaDAO();
        pronosticaDao.create(pronostico);
        
        JOptionPane.showMessageDialog(eventPanel, "Pronostico añadido correctamente!");
    }//GEN-LAST:event_addBetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBet;
    private javax.swing.JLabel eventIdFromLabel;
    private javax.swing.JList<String> eventList;
    private javax.swing.JPanel eventPanel;
    private javax.swing.JLabel eventTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblVersus;
    private javax.swing.JTextField localFieldGoals;
    private javax.swing.JLabel localTeamName;
    private javax.swing.JButton profileBtn;
    private javax.swing.JTextField visitFieldGoals;
    private javax.swing.JLabel visitTeamName;
    // End of variables declaration//GEN-END:variables
}
