/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.proyectofinalprogramacion.encuentro.EncuentroDAO;
import equipos.Equipo;
import equipos.EquiposDAO;
import java.sql.Date;
import java.sql.Time;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Usuario
 */
public class NewEvent extends javax.swing.JFrame {

    DefaultComboBoxModel localComboBoxModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel visitComboBoxModel = new DefaultComboBoxModel<>();
    private List<Equipo> allTeams;
    private PanelAdm panelAdmin;
    
    /**
     * Creates new form NewEvent
     */
    public NewEvent() {
        initComponents();
        setComboboxModelOnInstance();
        settingListenersForComboboxes();
        setupLogicComponents();
    }
    
    public NewEvent(PanelAdm panelAdmin) {
        initComponents();
        setComboboxModelOnInstance();
        settingListenersForComboboxes();
        setupLogicComponents();
        
        this.panelAdmin = panelAdmin;
    }

    private void setupLogicComponents() {
        visitComboBox.setEnabled(false);
        restartLocalTeams.setEnabled(false);

    }

    private void setComboboxModelOnInstance() {
        localComboBox.setModel(localComboBoxModel);
        visitComboBox.setModel(visitComboBoxModel);

        EquiposDAO equiposDao = new EquiposDAO();
        allTeams = equiposDao.obtenerTodosLosEquipos();

        localComboBoxModel.addAll(allTeams);
        visitComboBoxModel.addAll(allTeams);
    }

    private void settingListenersForComboboxes() {
        // Listener para el COMBO LOCAL
        localComboBox.addActionListener(e -> {
            // Obtenemos el equipo local que acaba de ser seleccionado
            Equipo equipoLocalSeleccionado = (Equipo) localComboBox.getSelectedItem();
            restartLocalTeams.setEnabled(true);
            visitComboBox.setEnabled(true);
            localComboBox.setEnabled(false);
            updateVisitCombobox(equipoLocalSeleccionado);
        });
    }

    /**
     * Actualiza el modelo del ComboBox de Visita. Quita el equipo que fue
     * seleccionado como Local.
     */
    private void updateVisitCombobox(Equipo equipoLocalSeleccionado) {
        visitComboBoxModel.removeAllElements();

        // Llenar el modelo de visita con todos los equipos...
        for (int i = 0; i < allTeams.size(); i++) {
            if (allTeams.get(i).getIdEquipo() != equipoLocalSeleccionado.getIdEquipo()) {
                visitComboBoxModel.addElement(allTeams.get(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner4 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        localComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        visitComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        saveEventBtn = new javax.swing.JButton();
        restartLocalTeams = new javax.swing.JButton();
        dayTxt = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        monthTxt = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        startTimeHour = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        startTimeMinute = new javax.swing.JSpinner();
        endTimeHour = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        endTimeMinute = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo Encuentro");

        jLabel2.setText("Equipo Locatario");

        localComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Equipo Visitante");

        visitComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("VS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha");

        saveEventBtn.setText("Guardar Encuentro");
        saveEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEventBtnActionPerformed(evt);
            }
        });

        restartLocalTeams.setText("Reiniciar");
        restartLocalTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartLocalTeamsActionPerformed(evt);
            }
        });

        dayTxt.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("/");

        monthTxt.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("/");

        yearTxt.setModel(new javax.swing.SpinnerNumberModel(2025, 2025, 2500, 1));

        jLabel8.setText("dia");

        jLabel9.setText("mes");

        jLabel10.setText("año");

        jLabel11.setText("Hora Inicio");

        startTimeHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText(":");

        startTimeMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        endTimeHour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText(":");

        endTimeMinute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel14.setText("Hora Fin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(localComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(startTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(startTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(endTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(endTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 7, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(saveEventBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(restartLocalTeams)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(364, 364, 364))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(localComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(restartLocalTeams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(monthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(startTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(startTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endTimeHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(endTimeMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(saveEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEventBtnActionPerformed
        int day = (int) dayTxt.getValue();
        int month = (int) monthTxt.getValue();
        int year = (int) yearTxt.getValue();
        int startTimeHour = (int) this.startTimeHour.getValue();
        int startTimeMinute = (int) this.startTimeMinute.getValue();
        int endTimeHour = (int) this.endTimeHour.getValue();
        int endTimeMinute = (int) this.endTimeMinute.getValue();

        Calendar calendarDate = Calendar.getInstance();
        calendarDate.set(year, month, day);

        Calendar calendarStartTime = Calendar.getInstance();
        calendarStartTime.set(Calendar.HOUR_OF_DAY, startTimeHour);
        calendarStartTime.set(Calendar.MINUTE, startTimeMinute);
        calendarStartTime.set(Calendar.SECOND, 0);
        calendarStartTime.set(Calendar.MILLISECOND, 0);

        Calendar calendarEndTime = Calendar.getInstance();
        calendarEndTime.set(Calendar.HOUR_OF_DAY, endTimeHour);
        calendarEndTime.set(Calendar.MINUTE, endTimeMinute);
        calendarEndTime.set(Calendar.SECOND, 0);
        calendarEndTime.set(Calendar.MILLISECOND, 0);

        Date dateEventForDB = new Date(calendarDate.getTimeInMillis());
        Time startTime = new Time(calendarStartTime.getTimeInMillis());
        Time endTime = new Time(calendarEndTime.getTimeInMillis());
        String eventState = "habilitado";
        Equipo localTeamSelected = (Equipo) localComboBox.getSelectedItem();
        Equipo visitTeamSelected = (Equipo) visitComboBox.getSelectedItem();
        
        System.out.println("Local ID: " + localTeamSelected.getIdEquipo());
        System.out.println("Visit ID: " + visitTeamSelected.getIdEquipo());
        System.out.println("Equipo local: " + localTeamSelected.getNombre() + "vs Equipo Visita: " + visitTeamSelected.getNombre());
        
        
        EncuentroDAO encuentroDao = new EncuentroDAO();
        
        encuentroDao.agregarEncuentro(
                dateEventForDB,
                startTime,
                endTime,
                eventState,
                localTeamSelected.getIdEquipo(),
                visitTeamSelected.getIdEquipo()
        );
        
        this.panelAdmin.setEventsIntoEventListModel();
        this.dispose();

    }//GEN-LAST:event_saveEventBtnActionPerformed

    private void restartLocalTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartLocalTeamsActionPerformed
        visitComboBoxModel.removeAllElements();
        localComboBox.setEnabled(true);
        visitComboBox.setEnabled(false);
        restartLocalTeams.setEnabled(false);
    }//GEN-LAST:event_restartLocalTeamsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner dayTxt;
    private javax.swing.JSpinner endTimeHour;
    private javax.swing.JSpinner endTimeMinute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JComboBox<String> localComboBox;
    private javax.swing.JSpinner monthTxt;
    private javax.swing.JButton restartLocalTeams;
    private javax.swing.JButton saveEventBtn;
    private javax.swing.JSpinner startTimeHour;
    private javax.swing.JSpinner startTimeMinute;
    private javax.swing.JComboBox<String> visitComboBox;
    private javax.swing.JSpinner yearTxt;
    // End of variables declaration//GEN-END:variables
}
