/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import equipos.EquiposDAO;
import equipos.Equipo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class NewTeam extends javax.swing.JFrame {
    
    private Equipo teamSelected;
    private PanelAdm adminPanel;

    /**
     * Creates new form NewTeam
     */
    public NewTeam() {
        initComponents();
        disableNormalWindowBehaviorOnClose();
    }
    
    public NewTeam(PanelAdm adminPanel) {
        initComponents();
        this.adminPanel = adminPanel;
        disableNormalWindowBehaviorOnClose();
    }
    
    public NewTeam(Equipo teamSelected, PanelAdm adminPanel) {
        initComponents();
        this.teamSelected = teamSelected;
        this.adminPanel = adminPanel;
        setEdittedValues();
        disableNormalWindowBehaviorOnClose();
    }
    
    private void disableNormalWindowBehaviorOnClose() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                closeWindow();
            }
        });
    }
    
    private void closeWindow(){
        this.dispose();
    }
    
    private void setEdittedValues () {
        teamNameTxt.setText(this.teamSelected.getNombre());
        title.setText("Editar equipo: " + this.teamSelected.getNombre());
        teamBtnAction.setText("Guardar cambios");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        teamNameTxt = new javax.swing.JTextField();
        teamBtnAction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Añadir Nuevo Equipo");

        backBtn.setText("Volver");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        teamBtnAction.setText("Añadir");
        teamBtnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamBtnActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamBtnAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(title)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(17, 17, 17))))
                    .addComponent(teamNameTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamBtnAction, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamBtnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamBtnActionActionPerformed
        String teamName = teamNameTxt.getText();
        
        if(teamName.isBlank() || teamName.isEmpty()){
            JOptionPane.showMessageDialog(
                    this,
                    "El nombre del equipo es obligatorio.",
                    "Campos obligatorios",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        EquiposDAO equipoDao = new EquiposDAO();
        Equipo newTeam = new Equipo(teamName);
        
        
        if( this.adminPanel != null && this.teamSelected != null ) {
            // Si entro en este if, significa que estoy actualizando un equipo
            newTeam.setIdEquipo(this.teamSelected.getIdEquipo());
            System.out.println("Dentro NewTeam: " + newTeam.getIdEquipo() + " - Nombre: " + newTeam.getNombre());
            equipoDao.actualizarEquipo(newTeam);
            JOptionPane.showMessageDialog(rootPane, "Equipo "+ newTeam.getNombre() + " actualizado exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.adminPanel.setTeamsIntoTeamListModel();
            this.dispose();
            return;
        }
        
        equipoDao.agregarEquipo(newTeam);
        JOptionPane.showMessageDialog(rootPane, "Equipo "+newTeam.getNombre()+ " creado exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
        this.adminPanel.setTeamsIntoTeamListModel();
        this.dispose();
        
        
    }//GEN-LAST:event_teamBtnActionActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton teamBtnAction;
    private javax.swing.JTextField teamNameTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
