/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.mycompany.proyectofinalprogramacion.encuentro.Encuentro;
import com.mycompany.proyectofinalprogramacion.encuentro.EncuentroDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ResultMatchWindow extends javax.swing.JFrame {
    
    private Encuentro encuentro;
    private EncuentroDAO encuentroDao = new EncuentroDAO();
    private PanelAdm panelAdmin;
    
    public ResultMatchWindow(Encuentro encuentro, PanelAdm panelAdmin){
        initComponents();
        this.encuentro = encuentro;
        this.panelAdmin = panelAdmin;
        setEventValuesIntoFields();
        disableNormalWindowBehaviorOnClose();
    }
    
    private void disableNormalWindowBehaviorOnClose() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                closeWindow();
            }
        });
    }

    private void closeWindow() {
        this.dispose();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        localTeamName = new javax.swing.JLabel();
        localTeamGoals = new javax.swing.JTextField();
        visitTeamGoals = new javax.swing.JTextField();
        visitTeamName = new javax.swing.JLabel();
        saveResultBtn = new javax.swing.JButton();
        cancelResultBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Resultado del partido");

        localTeamName.setText("localTeamName");

        visitTeamName.setText("visitTeamName");

        saveResultBtn.setBackground(new java.awt.Color(0, 153, 51));
        saveResultBtn.setText("Guardar resultado");
        saveResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveResultBtnActionPerformed(evt);
            }
        });

        cancelResultBtn.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(localTeamName)
                            .addComponent(localTeamGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visitTeamName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(visitTeamGoals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(saveResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelResultBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(visitTeamName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visitTeamGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(32, 32, 32)
                        .addComponent(localTeamName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localTeamGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(saveResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setEventValuesIntoFields () {
        localTeamName.setText(this.encuentro.getNombreLocal());
        visitTeamName.setText(this.encuentro.getNombreVisita());
    }
    
    
    
    private void saveResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveResultBtnActionPerformed
        String localGoals = localTeamGoals.getText();
        String visitGoals = visitTeamGoals.getText();
        
        this.panelAdmin.setMatchManuallyGoals(encuentro, Integer.parseInt(localGoals), Integer.parseInt(visitGoals));
        JOptionPane.showMessageDialog(this, "Goles configurados correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_saveResultBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelResultBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField localTeamGoals;
    private javax.swing.JLabel localTeamName;
    private javax.swing.JButton saveResultBtn;
    private javax.swing.JLabel title;
    private javax.swing.JTextField visitTeamGoals;
    private javax.swing.JLabel visitTeamName;
    // End of variables declaration//GEN-END:variables
}
